#
# Title: Example Application Configuration
# Authors: Malachi Harris & Luke Hamann
# Date: 2024-09-09
# Updated: 2024-09-13
# Purpose: This file provides a format for the application's configuration file.
#

SECRET_KEY = ""
