[project]
name = "bookmarkapp"
version = "1.0"
description = "A web application for managing bookmarks"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
